# Generated by Django 2.2.6 on 2019-10-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veb_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcomplprogects',
            name='img_main',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/houses/', verbose_name='Заставка'),
        ),
    ]
