# Generated by Django 2.2.6 on 2019-10-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veb_site', '0002_auto_20191011_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcomplprogects',
            name='img_10',
            field=models.ImageField(blank=True, null=True, upload_to='images/houses/', verbose_name='Изо_10'),
        ),
        migrations.AddField(
            model_name='rcomplprogects',
            name='img_8',
            field=models.ImageField(blank=True, null=True, upload_to='images/houses/', verbose_name='Изо_8'),
        ),
        migrations.AddField(
            model_name='rcomplprogects',
            name='img_9',
            field=models.ImageField(blank=True, null=True, upload_to='images/houses/', verbose_name='Изо_9'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='img_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/houses/', verbose_name='Изо_1'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/houses/', verbose_name='Изо_2'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='img_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/houses/', verbose_name='Изо_3'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='img_4',
            field=models.ImageField(blank=True, null=True, upload_to='images/houses/', verbose_name='Изо_4'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='img_5',
            field=models.ImageField(blank=True, null=True, upload_to='images/houses/', verbose_name='Изо_5'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='img_6',
            field=models.ImageField(blank=True, null=True, upload_to='images/houses/', verbose_name='Изо_6'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='img_7',
            field=models.ImageField(blank=True, null=True, upload_to='images/houses/', verbose_name='Изо_7'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='img_main',
            field=models.ImageField(blank=True, null=True, upload_to='images/houses/', verbose_name='Заставка'),
        ),
    ]
