# Generated by Django 2.2.6 on 2019-10-11 11:00

from django.db import migrations, models
import veb_site.utils


class Migration(migrations.Migration):

    dependencies = [
        ('veb_site', '0003_auto_20191011_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcomplprogects',
            name='img_main',
            field=models.ImageField(blank=True, null=True, upload_to=veb_site.utils.get_path, verbose_name='Заставка'),
        ),
    ]
