# Generated by Django 2.2.6 on 2019-10-11 11:16

from django.db import migrations, models
import veb_site.utils


class Migration(migrations.Migration):

    dependencies = [
        ('veb_site', '0004_auto_20191011_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcomplprogects',
            name='img_1',
            field=models.ImageField(blank=True, null=True, upload_to=veb_site.utils.get_path, verbose_name='Изо_1'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='img_10',
            field=models.ImageField(blank=True, null=True, upload_to=veb_site.utils.get_path, verbose_name='Изо_10'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to=veb_site.utils.get_path, verbose_name='Изо_2'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='img_3',
            field=models.ImageField(blank=True, null=True, upload_to=veb_site.utils.get_path, verbose_name='Изо_3'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='img_4',
            field=models.ImageField(blank=True, null=True, upload_to=veb_site.utils.get_path, verbose_name='Изо_4'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='img_5',
            field=models.ImageField(blank=True, null=True, upload_to=veb_site.utils.get_path, verbose_name='Изо_5'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='img_6',
            field=models.ImageField(blank=True, null=True, upload_to=veb_site.utils.get_path, verbose_name='Изо_6'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='img_7',
            field=models.ImageField(blank=True, null=True, upload_to=veb_site.utils.get_path, verbose_name='Изо_7'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='img_8',
            field=models.ImageField(blank=True, null=True, upload_to=veb_site.utils.get_path, verbose_name='Изо_8'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='img_9',
            field=models.ImageField(blank=True, null=True, upload_to=veb_site.utils.get_path, verbose_name='Изо_9'),
        ),
    ]
