# Generated by Django 2.2.6 on 2019-10-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veb_site', '0005_auto_20191011_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcomplprogects',
            name='bahtrooms',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=0, null=True, verbose_name='КоличествоСанузлов'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='bedrooms',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=0, null=True, verbose_name='КоличествоСпален'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='floor',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=1, null=True, verbose_name='Этажность'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='garage',
            field=models.TextField(choices=[('Нет', 'Нет'), ('Да', 'Да')], default='Нет', max_length=3, null=True, verbose_name='НаличиеГаража'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='typing',
            field=models.CharField(choices=[('houses', 'Дома'), ('hotels', 'Отели'), ('complexes', 'Жив. комплексы'), ('ets', 'Мойки, заправки и т.д.'), ('done_projects', 'Готовый проект')], db_index=True, max_length=150, null=True, verbose_name='ВидПроекта'),
        ),
    ]
