# Generated by Django 2.2.6 on 2019-10-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veb_site', '0007_auto_20191012_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcomplprogects',
            name='all_square',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='ОбщаяПлощадь'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='angle_roof',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='УголНаклонаКровли'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='bahtrooms',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=0, null=True, verbose_name='КоличествоСанузлов'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='bedrooms',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=0, null=True, verbose_name='КоличествоСпален'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='coob',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Кубатура'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='description',
            field=models.TextField(blank=True, default='', max_length=400, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='floor',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=1, null=True, verbose_name='Этажность'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='foundation',
            field=models.TextField(blank=True, default='', max_length=150, null=True, verbose_name='Фундамент'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='garage',
            field=models.TextField(blank=True, choices=[('Нет', 'Нет'), ('Да', 'Да')], default='Нет', max_length=3, null=True, verbose_name='НаличиеГаража'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='ВысотаЗдания'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='height_ceiling',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='ВысотаПотолка'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='housetop',
            field=models.TextField(blank=True, default='', max_length=150, null=True, verbose_name='Кровля'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='live_square',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='ЖилаяПлощадь'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='min_length',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='МинимальныйРазмерУчастка_длина'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='min_width',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='МинимальныйРазмерУчастка_ширина'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='overlap',
            field=models.TextField(blank=True, default='', max_length=150, null=True, verbose_name='Перекрытие'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='roof_square',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='ПлощадьКрыши'),
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='walls',
            field=models.TextField(blank=True, default='', max_length=150, null=True, verbose_name='Стены'),
        ),
    ]
