# Generated by Django 2.2.6 on 2019-10-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veb_site', '0008_auto_20191012_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcomplprogects',
            name='author',
            field=models.CharField(choices=[('Иванов', 'Иванов'), ('Петров', 'Петров'), ('Сидоров', 'Сидоров')], db_index=True, max_length=150, null=True, verbose_name='АвторПроекта'),
        ),
    ]
