# Generated by Django 2.2.6 on 2019-10-13 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veb_site', '0010_auto_20191013_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rcomplprogects',
            options={'verbose_name': 'Проекты'},
        ),
    ]
