# Generated by Django 2.2.6 on 2019-10-13 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veb_site', '0011_auto_20191013_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rcomplprogects',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
