# Generated by Django 2.2.6 on 2019-10-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veb_site', '0012_auto_20191013_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcomplprogects',
            name='typing',
            field=models.CharField(choices=[('houses', 'Дома'), ('hotels', 'Отели'), ('complexes', 'Жив. комплексы'), ('ets', 'Мойки, заправки и т.д.'), ('done_projects', 'Готовые проекты')], db_index=True, default='houses', max_length=150, null=True, verbose_name='ВидПроекта'),
        ),
    ]
