# Generated by Django 2.2.6 on 2019-10-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veb_site', '0013_auto_20191013_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='rContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.CharField(max_length=150, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=150, verbose_name='Электронная почта')),
                ('telephone', models.CharField(max_length=150, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Контактные данные',
                'verbose_name_plural': 'Контактные данные',
            },
        ),
        migrations.AlterField(
            model_name='rcomplprogects',
            name='author',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('Test', 'Test'), ('Test1', 'Test1')], db_index=True, max_length=150, null=True, verbose_name='АвторПроекта'),
        ),
    ]
