# Generated by Django 2.2.6 on 2019-10-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veb_site', '0014_auto_20191014_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcontacts',
            name='adres',
            field=models.CharField(max_length=150, verbose_name='Адрес'),
        ),
    ]
